In [1]:
# Assignment 3: Data Cleaning

In [9]:
# importing pandas library

import pandas as pd

In [10]:
# creating dataset with missing values

employee_dataframe = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Anuj"],
    "Age": [25, None, 29],
    "Salary": [30000, 40000, None]
})

employee_dataframe

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya   NaN  40000.0
2   Anuj  29.0      NaN

In [11]:
# 1. Detect missing values

employee_dataframe.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True

In [12]:
# 2. Replace missing Age with mean

# calculating mean
mean_age = employee_dataframe["Age"].mean()
print("Mean age:", mean_age)

# replacing missing age with mean_age
employee_dataframe["Age"] = employee_dataframe["Age"].fillna(mean_age)

employee_dataframe

Mean age: 27.0

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya  27.0  40000.0
2   Anuj  29.0      NaN

In [13]:
# 3. Replace missing Salary with 0

employee_dataframe["Salary"] = employee_dataframe["Salary"].fillna(0)

employee_dataframe

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya  27.0  40000.0
2   Anuj  29.0      0.0