In [1]:
# Assignment 2: Pandas DataFrame Creation

In [2]:
# importing pandas library 

import pandas as pd

In [12]:
# Creating Employee DataFrame

employee_dataframe = pd.DataFrame({
    "Name": ["Naman", "Ronaldo", "Messi", "Virat"],
    "Age": [23, 30, 28, 35],
    "Department": ["IT", "HR", "Finance", "IT"],
    "Salary": [30000, 50000, 45000, 60000]
})

employee_dataframe

      Name  Age Department  Salary
0    Naman   23         IT   30000
1  Ronaldo   30         HR   50000
2    Messi   28    Finance   45000
3    Virat   35         IT   60000

In [13]:
# 1. Show first 2 rows

employee_dataframe.head(2)

      Name  Age Department  Salary
0    Naman   23         IT   30000
1  Ronaldo   30         HR   50000

In [14]:
# 2. Show summary statistics

employee_dataframe.describe()

             Age   Salary
count   4.000000      4.0
mean   29.000000  46250.0
std     4.966555  12500.0
min    23.000000  30000.0
25%    26.750000  41250.0
50%    29.000000  47500.0
75%    31.250000  52500.0
max    35.000000  60000.0

In [18]:
# 3. Display only IT employees

employee_dataframe[employee_dataframe["Department"] == "IT"]

    Name  Age Department  Salary   Bonus
0  Naman   23         IT   30000  3000.0
3  Virat   35         IT   60000  6000.0

In [19]:
# 4. Add new column: bonus

employee_dataframe["Bonus"] = employee_dataframe["Salary"] * 0.10

employee_dataframe

      Name  Age Department  Salary   Bonus
0    Naman   23         IT   30000  3000.0
1  Ronaldo   30         HR   50000  5000.0
2    Messi   28    Finance   45000  4500.0
3    Virat   35         IT   60000  6000.0